### ISSUE TITLE
External scanner

### ISSUE THREAD

**Issue by 314eter** [Kerl13/tree-sitter-menhir#1]
I noticed some problems with the external scanner:

- You're scanning headers, actions an attributes with the opening and closing delimiters included. This will be a problem if you want to use grammar injections later to parse the ocaml code (as in [tree-sitter-ocamllex](https://github.com/314eter/tree-sitter-ocamllex)).

- `postlude`, `line_comment` and `comment` can be parsed with normal tree-sitter rules, there is no need for an external scanner.

- In tree-sitter/tree-sitter-ocaml@d2bd17d4f8667adbf4743f0778ffcc2662826a8c I solved the problem that `(* '*)` and others are not recognized as comments. The fix is rather ugly because external scanners can't backtrack, but I don't think there's another way.

There are some cases left where valid OCaml code in actions is not correctly parsed, but these are bugs in Menhir too.

**Comment by 314eter** [comment]
I'm going to continue the conversation of tree-sitter/tree-sitter#280 here.

Tree-sitter-ocaml has a rule for strings, but uses an external scanner for strings in comments. OCaml comments (which can be nested) are impossible to parse with a single token, which is required for extras. But headers, actions, attributes, etc. are not extras, so it should be possible to parse them with normal rules.

**Comment by Kerl13** [comment]
You're right about strings, (line) comments and the postlude. they should be parsed using normal tree sitter rules.

But to me, actions seem very similar to comments in the sense that you can nest curly braces. For instance:
```
{ { x = { y = 0 } } }
```

Moreover, what about examples like this?
```
%{ let s = " %}" %}
```

I'm not sure, but I think the external scanner can't be avoided if we want a single token.

**Comment by 314eter** [comment]
You're right that it can't be a single token, but for actions that's not required.

**Comment by Kerl13** [comment]
Isn't this required for grammar injection? Or are you suggesting that grammar injection is not relevant for actions?

**Comment by Kerl13** [comment]
It is true that actions are usually very short snippets of code and that `$`-expressions (like `$1`) seem difficult to handle

**Comment by 314eter** [comment]
For grammar injection it has to be one node in the syntax tree, but that's still possible by using hidden rules.

**Comment by Kerl13** [comment]
ok that's nice.

But then why not doing the same for OCaml comments? This seems very similar to me

**Comment by 314eter** [comment]
$-expressions are already handled in tree-sitter/tree-sitter-ocaml#18 (the ocamlyacc grammar I was talking about never got finished)

OCaml comments are required to be single tokens because they are in extras (they can appear anywhere), and extras can contain tokens only.

**Comment by Kerl13** [comment]
That's good news.

Got it
